files:
  include: 'src/**/*.scss'
options:
  max-warnings: 10
  merge-default-rules: false
rules:
  attribute-quotes:
    - 2
    -
      include: false
  bem-depth:
    - 2
    -
      max-depth: 1
  border-zero: 0
  brace-style:
    - 2
    -
      allow-single-line: false
      style: 'stroustrup'
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedbem'
  clean-import-paths:
    - 2
    -
      filename-extension: false
      leading-underscore: false
  declarations-before-nesting: 2
  empty-args:
    - 2
    -
      include: false
  empty-line-between-blocks:
    - 2
    -
      allow-single-line-rulesets: false
      include: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 1
    -
      include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  hex-length:
    - 2
    -
      style: 'short'
  hex-notation:
    - 2
    -
      style: 'uppercase'
  id-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    -
      include: false
  max-file-line-count:
    - 1
    -
      length: 200
  max-line-length:
    - 1
    -
      length: 80
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  mixins-before-declarations: 0
  nesting-depth:
    - 2
    -
      max-depth: 2
  no-attribute-selectors: 0
  no-color-hex: 1
  no-color-keywords: 0
  no-color-literals:
    - 1
    -
      allow-map-identifiers: true
      allow-rgba: false
      allow-variable-identifiers: true
  no-combinators: 1
  no-css-comments: 2
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 1
  no-extends: 1
  no-ids: 1
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-whitespace: 1
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-url-domains: 2
  no-url-protocols:
    - 2
    -
      allow-protocol-relative-urls: false
  no-vendor-prefixes:
    - 2
    -
      ignore-non-standard: true
  no-warn: 0
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedbem'
  property-sort-order:
    - 2
    -
      order: 'alphabetical'
  property-units: 0
  pseudo-element: 2
  quotes:
    - 2
    -
      style: 'single'
  shorthand-values:
    - 2
    -
      allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 2
  space-after-bang:
    - 2
    -
      include: false
  space-after-colon:
    - 2
    -
      include: true
  space-after-comma:
    - 2
    -
      include: true
  space-around-operator:
    - 2
    -
      include: true
  space-before-bang:
    - 2
    -
      include: true
  space-before-brace:
    - 2
    -
      include: true
  space-before-colon:
    - 2
    -
      include: false
  space-between-parens:
    - 2
    -
      include: true
  trailing-semicolon:
    - 2
    -
      include: true
  url-quotes: 0
  variable-for-property: 0
  variable-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  zero-unit:
    - 2
    -
      include: false
